export const TO_MOVE = 'TO_MOVE' // 更加顺滑跳转移动
export const CHANGE_MODE = 'CHANGE_MODE'// 更改现在的模式
export const SHOW_LOADING = 'SHOW_LOADING'//  加载动画展示
export const HIDE_LOADING = 'HIDE_LOADING'//  加载动画隐藏
export const LOGIN = 'LOGIN' //  登录成功
export const LOGOUT = 'LOGOUT' //  退出登录
export const USERNAME = 'USERNAME'
export const SHOW_ANSWER = 'SHOW_ANSWER' //  展现答案
export const DEEP_CLONE = 'DEEP_CLONE'
